/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package course_management_system;

import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.sql.*;

public class CompleteInstructorRegistration extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement pst;

    public CompleteInstructorRegistration() {
        initComponents();
        conn = db.database_db();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_fName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Sname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_age = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_male = new javax.swing.JRadioButton();
        txt_female = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txt_Uname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        warning = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_password = new javax.swing.JPasswordField();
        warning_password = new javax.swing.JLabel();
        Cuppercase = new javax.swing.JCheckBox();
        Cspecialcharacter = new javax.swing.JCheckBox();
        Cgreaterthan8 = new javax.swing.JCheckBox();
        Clowercase = new javax.swing.JCheckBox();
        Cnumbers = new javax.swing.JCheckBox();
        MakePasswordVisible = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        txt_phone = new javax.swing.JTextField();
        Clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INSTRUCTOR REGISTRATION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poor Richard", 1, 24), new java.awt.Color(0, 51, 255))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        jLabel2.setText("FIRST NAME");

        txt_fName.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        txt_fName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204), 2));

        jLabel3.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        jLabel3.setText("SECOND NAME");

        txt_Sname.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        txt_Sname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204), 2));

        jLabel4.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        jLabel4.setText("EMAIL");

        txt_email.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        txt_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204), 2));

        jLabel5.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        jLabel5.setText("AGE");

        txt_age.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        txt_age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204), 2));
        txt_age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ageKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        jLabel6.setText("GENDER");

        genderButtonGroup.add(txt_male);
        txt_male.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        txt_male.setText("Male");

        genderButtonGroup.add(txt_female);
        txt_female.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        txt_female.setText("Female");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setText("USERNAME");

        txt_Uname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_Uname.setToolTipText("Enter User Name");
        txt_Uname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
        jLabel8.setText("PASSWORD");

        jButton1.setBackground(new java.awt.Color(204, 0, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageFolder/Calculate.png"))); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt_password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_password.setToolTipText("Enter Password");
        txt_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_passwordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_passwordKeyTyped(evt);
            }
        });

        Cuppercase.setBackground(new java.awt.Color(153, 153, 255));
        Cuppercase.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Cuppercase.setText("UpperCase");

        Cspecialcharacter.setBackground(new java.awt.Color(153, 153, 255));
        Cspecialcharacter.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Cspecialcharacter.setText("Special Character");

        Cgreaterthan8.setBackground(new java.awt.Color(153, 153, 255));
        Cgreaterthan8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Cgreaterthan8.setText("Greater Than 8");

        Clowercase.setBackground(new java.awt.Color(153, 153, 255));
        Clowercase.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Clowercase.setText("LowerCase");

        Cnumbers.setBackground(new java.awt.Color(153, 153, 255));
        Cnumbers.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Cnumbers.setText("Numbers");

        MakePasswordVisible.setBackground(new java.awt.Color(153, 153, 255));
        MakePasswordVisible.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        MakePasswordVisible.setText("Unvail");
        MakePasswordVisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakePasswordVisibleActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        jLabel9.setText("PHONE");

        txt_phone.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        txt_phone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204), 2));
        txt_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phoneActionPerformed(evt);
            }
        });
        txt_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_phoneKeyTyped(evt);
            }
        });

        Clear.setBackground(new java.awt.Color(204, 0, 204));
        Clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Clear.setForeground(new java.awt.Color(255, 255, 255));
        Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageFolder/erase-128.png"))); // NOI18N
        Clear.setText("ADD NEW");
        Clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageFolder/AAAA.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(warning, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txt_fName, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_Sname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(193, 193, 193)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Cuppercase)
                                        .addGap(18, 18, 18)
                                        .addComponent(Cspecialcharacter)
                                        .addGap(18, 18, 18)
                                        .addComponent(Cnumbers))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Cgreaterthan8)
                                        .addGap(18, 18, 18)
                                        .addComponent(Clowercase))
                                    .addComponent(warning_password, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txt_Uname, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                                        .addGap(34, 34, 34)
                                        .addComponent(MakePasswordVisible))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(282, 282, 282)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_male, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(txt_female)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_fName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Sname, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(txt_Uname, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(warning_password, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MakePasswordVisible))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cuppercase)
                            .addComponent(Cspecialcharacter)
                            .addComponent(Cnumbers))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cgreaterthan8)
                            .addComponent(Clowercase)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(warning, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_female)
                            .addComponent(txt_male)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ageKeyTyped
        if (txt_age.getText().length() > 9) {
            evt.consume();
            txt_age.setForeground(Color.RED);
            warning.setText("");
            warning.setForeground(Color.RED);
            warning.setText(warning.getText() + " Phone number cannot be greater than 9 digits");
        }
        if (txt_age.getText().length() <= 9) {

            txt_age.setForeground(Color.BLACK);
            warning.setText("");
        }
    }//GEN-LAST:event_txt_ageKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        txt_male.setActionCommand("Male");
        txt_female.setActionCommand("Female");
        conn = db.database_db();
        int opt = JOptionPane.showConfirmDialog(null, "Are you sure you want to Add Instructor?", "Create Account", JOptionPane.YES_NO_OPTION);
        if (opt == 0) {
            try {
                String user = txt_Uname.getText();
                String sql2 = "Select *from Instructor_Table where user_name=?";
                pst = conn.prepareStatement(sql2);
                pst.setString(1, user);
                ResultSet rs = pst.executeQuery();
                if (rs.isBeforeFirst()) {
                    rs.next();
                    JOptionPane.showMessageDialog(null, "Username " + txt_Uname.getText() + " Already Taken, Please choose another name", "Warning",
                            JOptionPane.WARNING_MESSAGE);
                }
            } catch (Exception e) {

            }
            if (txt_Uname.getText().length() == 0 || txt_password.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "You must enter a username or password", "Warning",
                        JOptionPane.WARNING_MESSAGE);
            } else {

                try {
                    String fname = txt_fName.getText();
                    String sname = txt_Sname.getText();
                    String gender = genderButtonGroup.getSelection().getActionCommand();
                    String age = txt_age.getText();
                    String email = txt_email.getText();
                    String phone = txt_phone.getText();
                    String username = txt_Uname.getText();
                    String password = txt_password.getText();

                    String sql = "INSERT INTO Instructor_Table(first_name,second_name,age,gender,phone,email,user_name,password) VALUES (?,?,?,?,?,?,?,?) ";

                    pst = conn.prepareStatement(sql);
                    pst.setString(1, fname);
                    pst.setString(2, sname);
                    pst.setString(3, age);
                    pst.setString(4, gender);
                    pst.setString(5, phone);
                    pst.setString(6, email);
                    pst.setString(7, username);
                    pst.setString(8, password);

                    if (pst.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(this, "Instructor was successfully Added ");
                    }

                } catch (Exception e) {

                    JOptionPane.showMessageDialog(this, "Instructor was not added " + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyReleased

    }//GEN-LAST:event_txt_passwordKeyReleased

    private void txt_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyTyped

        String upperCaseChars = "(.*[A-Z].*)";
        String lowerCaseChars = "(.*[a-z].*)";
        String numbers = "(.*[0-9].*)";
        String specialChars = "(.*[@,#,$,%].*$)";

        if (txt_password.getText().length() < 8
                || txt_password.getText().matches(upperCaseChars)
                || txt_password.getText().matches(lowerCaseChars)
                || txt_password.getText().matches(numbers)
                || txt_password.getText().matches(specialChars)) {
            warning_password.setText("Strong password");
            warning_password.setForeground(Color.BLUE);
            txt_password.setForeground(Color.BLUE);
        } else {
            warning_password.setText("make password Strong");
            warning_password.setForeground(Color.RED);
        }
        if (txt_password.getText().length() < 8) {
            warning_password.setText("weak password");
            warning_password.setForeground(Color.RED);
            txt_password.setForeground(Color.RED);
            Cgreaterthan8.setSelected(false);
        } else {
            Cgreaterthan8.setSelected(true);
        }

        if (!txt_password.getText().matches(upperCaseChars)) {
            warning_password.setText("weak password");
            warning_password.setForeground(Color.RED);
            txt_password.setForeground(Color.RED);
            Cuppercase.setSelected(false);
        } else {
            Cuppercase.setSelected(true);
        }

        if (!txt_password.getText().matches(lowerCaseChars)) {
            warning_password.setText("weak password");
            warning_password.setForeground(Color.RED);
            txt_password.setForeground(Color.RED);
            Clowercase.setSelected(false);
        } else {
            Clowercase.setSelected(true);
        }

        if (!txt_password.getText().matches(numbers)) {
            warning_password.setText("weak password");
            warning_password.setForeground(Color.RED);
            txt_password.setForeground(Color.RED);
            Cnumbers.setSelected(false);
        } else {
            Cnumbers.setSelected(true);
        }

        if (!txt_password.getText().matches(specialChars)) {
            warning_password.setText("weak password");
            warning_password.setForeground(Color.RED);
            txt_password.setForeground(Color.RED);
            Cspecialcharacter.setSelected(false);
        } else {
            Cspecialcharacter.setSelected(true);
        }
        if (txt_password.getText().isEmpty()) {
            warning_password.setText(null);
            txt_password.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_passwordKeyTyped

    private void MakePasswordVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakePasswordVisibleActionPerformed
        if (MakePasswordVisible.isSelected()) {
            txt_password.setEchoChar((char) 0);
        } else {
            txt_password.setEchoChar('*');
        }
    }//GEN-LAST:event_MakePasswordVisibleActionPerformed

    private void txt_phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phoneKeyTyped
        if (txt_phone.getText().length() > 9) {
            evt.consume();
            txt_phone.setForeground(Color.RED);
            warning.setText("");
            warning.setForeground(Color.RED);
            warning.setText(warning.getText() + " Phone number cannot be greater than 9 digits");
        }
        if (txt_phone.getText().length() <= 9) {

            txt_phone.setForeground(Color.BLACK);
            warning.setText("");
        }
        String numbers = "(.*[0-9].*)";
        if (!txt_phone.getText().matches(numbers)) {
            warning.setText("Only Numbers");
            warning.setForeground(Color.RED);
            txt_phone.setForeground(Color.RED);

        } else {
            txt_phone.setForeground(Color.BLACK);
            warning.setForeground(Color.BLACK);
        }
        if (txt_phone.getText().isEmpty()) {
            warning.setText(null);
        }

    }//GEN-LAST:event_txt_phoneKeyTyped

    private void txt_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        clear();
    }//GEN-LAST:event_ClearActionPerformed
    public void clear() {

        txt_fName.setText(null);
        txt_Sname.setText(null);
        txt_male.setSelected(false);
        txt_female.setSelected(false);
        txt_age.setText(null);
        txt_email.setText(null);
        txt_phone.setText(null);
        txt_password.setText(null);
        txt_Uname.setText(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompleteInstructorRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompleteInstructorRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompleteInstructorRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompleteInstructorRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompleteInstructorRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Cgreaterthan8;
    private javax.swing.JButton Clear;
    private javax.swing.JCheckBox Clowercase;
    private javax.swing.JCheckBox Cnumbers;
    private javax.swing.JCheckBox Cspecialcharacter;
    private javax.swing.JCheckBox Cuppercase;
    private javax.swing.JCheckBox MakePasswordVisible;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField txt_Sname;
    private javax.swing.JTextField txt_Uname;
    public static javax.swing.JTextField txt_age;
    public static javax.swing.JTextField txt_email;
    public static javax.swing.JTextField txt_fName;
    public static javax.swing.JRadioButton txt_female;
    public static javax.swing.JRadioButton txt_male;
    private javax.swing.JPasswordField txt_password;
    public static javax.swing.JTextField txt_phone;
    private javax.swing.JLabel warning;
    private javax.swing.JLabel warning_password;
    // End of variables declaration//GEN-END:variables
}
