/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package course_management_system;

import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Tamnjong Larry
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGroundPanel = new javax.swing.JPanel();
        LoadingBar = new javax.swing.JProgressBar();
        loading = new javax.swing.JLabel();
        LoadingValue = new javax.swing.JLabel();
        dispaly = new javax.swing.JLabel();
        version = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        power = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        BackGroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        BackGroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoadingBar.setBackground(new java.awt.Color(51, 102, 255));
        LoadingBar.setForeground(new java.awt.Color(51, 51, 255));
        BackGroundPanel.add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 1020, 10));

        loading.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        loading.setText("0%");
        BackGroundPanel.add(loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 650, 50, 30));

        LoadingValue.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        LoadingValue.setText("CMS is about to start...");
        BackGroundPanel.add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 240, 40));

        dispaly.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        dispaly.setForeground(new java.awt.Color(0, 0, 255));
        dispaly.setText("Sotravonic is here to make life easier...");
        BackGroundPanel.add(dispaly, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 0, -1));

        version.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        version.setForeground(new java.awt.Color(0, 51, 255));
        BackGroundPanel.add(version, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("COURSE MANAGEMENT SYSTEM");
        BackGroundPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 630, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageFolder/00000.jpeg"))); // NOI18N
        BackGroundPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 720, 380));

        power.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        power.setForeground(new java.awt.Color(0, 204, 0));
        BackGroundPanel.add(power, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 240, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(BackGroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1021, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        SplashScreen sp = new SplashScreen();
        sp.setVisible(true);
        try {

            for (int i = 0; i <= 100; i++) {
                Thread.sleep(100);

                sp.loading.setText(i + "%");

                if (i == 10) {
                    sp.LoadingValue.setText("Loading Assets...");
                    sp.version.setText("SSJ IT SOLUTIONS");
                      sp.power.setText("SSJ IT SOLUTION");

                }
                if (i == 15) {
                    sp.LoadingValue.setText("Loading Module...");

                }
                if (i == 20) {
                    sp.LoadingValue.setText("Connecting to Database...");
                }
                if (i == 30) {
                    sp.LoadingValue.setText("Doing house cleaning...");
                    sp.version.setText("TAMNJONG LARRY");
                    

                }
                if (i == 40) {
                    sp.LoadingValue.setText("Checking for errors...");
                    sp.version.setText("BHAKTI");

                }
                if (i == 50) {
                    sp.LoadingValue.setText("Preparing for signin....");
                    sp.power.setText("WHITEBOARD INTERNSHIP PROGRAM");
                }
                if (i == 60) {
                    sp.LoadingValue.setText("Finalizing launch...");
                    sp.version.setText("APEKSHA");

                }
                if (i == 70) {
                    sp.LoadingValue.setText("Launching Application...");
                }
                if (i == 40) {
                    sp.LoadingValue.setText("welcome...");
                }
                if (i > 65) {
                    sp.version.setText("Version 1.0");
                }

                sp.LoadingBar.setValue(i);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        new SplashScreen().setVisible(false);
        StudentLogIn StudentLogIn = new StudentLogIn();
        StudentLogIn.setVisible(true);
        sp.dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGroundPanel;
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JLabel dispaly;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel loading;
    private javax.swing.JLabel power;
    private javax.swing.JLabel version;
    // End of variables declaration//GEN-END:variables
}
